project_name: terraform-provider-logentries
release:
  github:
    owner: depop
    name: terraform-provider-logentries
  name_template: '{{.Tag}}'
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  targets:
  - linux_amd64
  - darwin_amd64
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: terraform-provider-logentries
  lang: go
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
env_files:
  github_token: ~/.config/goreleaser/github_token
